import React from "react";

// ─── Page-level styles ────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
    root: {
        minHeight: "100vh",
        backgroundImage: "linear-gradient(rgba(10, 6, 24, 0.75), rgba(10, 6, 24, 0.75)), url('/images/parchment_dark.jpg')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        color: "#cc99ff",
        fontFamily: "Georgia, 'Times New Roman', serif",
        position: "relative",
        overflowX: "hidden",
    },
    noise: {
        position: "fixed",
        inset: 0,
        backgroundImage:
            "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
        pointerEvents: "none",
        zIndex: 0,
    },
    header: {
        textAlign: "center",
        padding: "52px 24px 32px",
        position: "relative",
        zIndex: 1,
        borderBottom: "1px solid #1a0a2e",
        background:
            "linear-gradient(180deg, rgba(20,8,50,0.9) 0%, rgba(6,2,16,0) 100%)",
    },
    headerRune: {
        color: "#6622aa",
        fontSize: 14,
        letterSpacing: 10,
        opacity: 0.6,
        marginBottom: 8,
    },
    title: {
        fontFamily: "Georgia, serif",
        fontSize: "clamp(28px, 5vw, 48px)",
        color: "#cc88ff",
        letterSpacing: 4,
        margin: "0 0 10px",
        textShadow:
            "0 0 40px rgba(180,80,255,0.35), 0 0 80px rgba(120,40,200,0.15)",
        fontWeight: "normal",
    },
    headerSub: {
        fontFamily: "monospace",
        fontSize: 12,
        color: "#664488",
        letterSpacing: 1.5,
        margin: "0 0 16px",
    },
    tabBar: {
        display: "flex",
        justifyContent: "center",
        gap: 2,
        padding: "16px 24px",
        borderBottom: "1px solid #1a0a2e",
        position: "relative",
        zIndex: 1,
    },
    tab: {
        background: "transparent",
        border: "1px solid #2a1a3a",
        borderRadius: 6,
        padding: "9px 24px",
        color: "#664488",
        fontFamily: "monospace",
        fontSize: 12,
        letterSpacing: 1.5,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    tabActive: {
        background: "rgba(80,20,120,0.3)",
        border: "1px solid #7733bb",
        color: "#cc88ff",
        boxShadow: "0 0 16px rgba(120,40,200,0.2)",
    },
    content: {
        maxWidth: 1100,
        margin: "0 auto",
        padding: "32px 20px 60px",
        position: "relative",
        zIndex: 1,
    },
    footer: {
        textAlign: "center",
        padding: "24px",
        borderTop: "1px solid #1a0a2e",
        position: "relative",
        zIndex: 1,
    },
    footerText: {
        fontFamily: "monospace",
        fontSize: 13,
        color: "#3a1a5a",
        letterSpacing: 2,
    },
};

// ─── Ingredient tab styles ────────────────────────────────────────────────────

export const ing: Record<string, React.CSSProperties> = {
    layout: {
        display: "grid",
        gridTemplateColumns: "220px 1fr",
        gap: 20,
        alignItems: "start",
    },
    sidebar: {
        display: "flex",
        flexDirection: "column",
        gap: 4,
        position: "sticky",
        top: 20,
    },
    sidebarTitle: {
        fontFamily: "monospace",
        fontSize: 12,
        color: "#3a1a5a",
        letterSpacing: 3,
        textTransform: "uppercase",
        padding: "0 10px 10px",
        borderBottom: "1px solid #1a0a2e",
        marginBottom: 4,
    },
    sidebarItem: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "8px 10px",
        background: "transparent",
        border: "1px solid transparent",
        borderRadius: 7,
        cursor: "pointer",
        transition: "all 0.15s",
        textAlign: "left",
        width: "100%",
    },
    sidebarItemText: {
        display: "flex",
        flexDirection: "column",
        gap: 2,
    },
    sidebarName: {
        fontFamily: "Georgia, serif",
        fontSize: 16,
    },
    sidebarRarity: {
        fontFamily: "monospace",
        fontSize: 11,
        color: "#443355",
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    detail: {
        minHeight: 400,
    },
};

// ─── Detail panel styles ──────────────────────────────────────────────────────

export const det: Record<string, React.CSSProperties> = {
    root: {
        flex: 1,
        backgroundImage: "linear-gradient(rgba(10, 6, 24, 0.75), rgba(10, 6, 24, 0.75)), url('/images/parchment_dark.jpg')",
        backgroundSize: "cover",
        border: "1px solid #2a1a3a",
        borderRadius: 12,
        padding: "28px 32px",
        display: "flex",
        flexDirection: "column",
        gap: 20,
    },
    header: {
        display: "flex",
        alignItems: "center",
        gap: 20,
    },
    headerText: {
        display: "flex",
        flexDirection: "column",
        gap: 6,
    },
    name: {
        fontFamily: "Georgia, serif",
        fontSize: 28,
        letterSpacing: 1,
        textShadow: "0 0 20px currentColor, 2px 2px 4px rgba(0,0,0,0.8)",
        fontWeight: "bold",
        lineHeight: 1,
    },
    latin: {
        fontFamily: "monospace",
        fontSize: 13,
        color: "#554466",
        fontStyle: "italic",
        letterSpacing: 1,
    },
    section: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    sectionTitle: {
        fontFamily: "monospace",
        fontSize: 12,
        color: "#6633aa",
        letterSpacing: 3,
        textTransform: "uppercase",
    },
    body: {
        fontFamily: "Georgia, serif",
        fontSize: 16,
        color: "#d0b0d0",
        lineHeight: 1.75,
        textShadow: "1px 1px 3px rgba(0,0,0,0.9)",
        margin: 0,
    },
    lore: {
        fontFamily: "Georgia, serif",
        fontSize: 15,
        color: "#a080b0",
        lineHeight: 1.75,
        fontStyle: "italic",
        textShadow: "1px 1px 2px rgba(0,0,0,0.9)",
        margin: 0,
    },
    valueRow: {
        display: "flex",
        gap: 8,
        flexWrap: "wrap",
    },
    valuePip: {
        width: 36,
        height: 36,
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "Georgia, serif",
        fontSize: 16,
        fontWeight: "bold",
    },
    valueNote: {
        fontFamily: "monospace",
        fontSize: 13,
        color: "#443355",
    },
    effectBox: {
        background: "rgba(40,10,70,0.75)",
        boxShadow: "inset 0 0 10px rgba(0,0,0,0.5)",
        border: "1px solid transparent",
        borderRadius: 8,
        padding: "14px 16px",
    },
    warningBox: {
        display: "flex",
        alignItems: "flex-start",
        gap: 10,
        background: "rgba(120,20,0,0.5)",
        border: "1px solid #661100",
        borderRadius: 8,
        padding: "12px 16px",
    },
    warningIcon: {
        color: "#ff4422",
        fontSize: 16,
        flexShrink: 0,
        marginTop: 1,
    },
    warningText: {
        fontFamily: "monospace",
        fontSize: 14,
        color: "#cc4422",
        lineHeight: 1.6,
        margin: 0,
    },
};

// ─── Omen tab styles ──────────────────────────────────────────────────────────

export const om: Record<string, React.CSSProperties> = {
    root: {
        display: "flex",
        flexDirection: "column",
        gap: 24,
    },
    intro: {
        fontFamily: "Georgia, serif",
        fontSize: 16,
        color: "#6a4a7a",
        lineHeight: 1.75,
        textAlign: "center",
        maxWidth: 640,
        margin: "0 auto",
        fontStyle: "italic",
    },
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(290px, 1fr))",
        gap: 16,
    },
    card: {
        background: "linear-gradient(160deg, #0a0618 0%, #110828 100%)",
        border: "1px solid #2a0a4a",
        borderRadius: 12,
        padding: "22px 24px",
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    cardIcon: {
        fontSize: 24,
        color: "#7733bb",
        opacity: 0.7,
    },
    cardTitle: {
        fontFamily: "Georgia, serif",
        fontSize: 20,
        color: "#cc88ff",
        letterSpacing: 1,
    },
    cardCards: {
        fontFamily: "monospace",
        fontSize: 12,
        color: "#443355",
        letterSpacing: 1,
    },
    divider: {
        height: 1,
        background: "linear-gradient(90deg, transparent, #3a1a5a, transparent)",
        margin: "2px 0",
    },
    effectLabel: {
        fontFamily: "monospace",
        fontSize: 11,
        color: "#6633aa",
        letterSpacing: 3,
        textTransform: "uppercase",
    },
    effect: {
        fontFamily: "Georgia, serif",
        fontSize: 15,
        color: "#cc99ff",
        lineHeight: 1.6,
    },
    stratLabel: {
        fontFamily: "monospace",
        fontSize: 11,
        color: "#446633",
        letterSpacing: 3,
        textTransform: "uppercase",
    },
    strat: {
        fontFamily: "Georgia, serif",
        fontSize: 15,
        color: "#88aa77",
        lineHeight: 1.7,
        margin: 0,
        fontStyle: "italic",
    },
};

// ─── Rules tab styles ─────────────────────────────────────────────────────────

export const rl: Record<string, React.CSSProperties> = {
    root: {
        display: "flex",
        flexDirection: "column",
        gap: 6,
        maxWidth: 760,
        margin: "0 auto",
    },
    intro: {
        fontFamily: "Georgia, serif",
        fontSize: 14,
        color: "#6a4a7a",
        lineHeight: 1.75,
        textAlign: "center",
        fontStyle: "italic",
        marginBottom: 16,
    },
    section: {
        background: "rgba(10,6,24,0.7)",
        border: "1px solid #1a0a2e",
        borderRadius: 8,
        overflow: "hidden",
    },
    sectionHeader: {
        display: "flex",
        alignItems: "center",
        gap: 14,
        width: "100%",
        background: "transparent",
        border: "none",
        padding: "15px 20px",
        cursor: "pointer",
        textAlign: "left",
        transition: "background 0.15s",
    },
    sectionNum: {
        fontFamily: "monospace",
        fontSize: 11,
        color: "#3a1a5a",
        letterSpacing: 1,
        flexShrink: 0,
    },
    sectionTitle: {
        fontFamily: "Georgia, serif",
        fontSize: 16,
        color: "#bb88ee",
        flex: 1,
        letterSpacing: 0.5,
    },
    chevron: {
        fontFamily: "monospace",
        fontSize: 10,
        color: "#6633aa",
        flexShrink: 0,
    },
    sectionBody: {
        padding: "4px 20px 20px 20px",
        display: "flex",
        flexDirection: "column",
        gap: 12,
        borderTop: "1px solid #1a0a2e",
    },
    ruleLine: {
        display: "flex",
        alignItems: "flex-start",
        gap: 12,
        paddingTop: 8,
    },
    ruleBullet: {
        color: "#5a2a8a",
        fontSize: 11,
        flexShrink: 0,
        marginTop: 3,
    },
    ruleText: {
        fontFamily: "Georgia, serif",
        fontSize: 14,
        color: "#8a6a9a",
        lineHeight: 1.7,
    },
};
