import React from "react";

export const s: Record<string, React.CSSProperties> = {
    overlay: {
        position: "fixed",
        inset: 0,
        background: "rgba(4, 2, 14, 0.82)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 90,
        backdropFilter: "blur(3px)",
        pointerEvents: "none",
    },
    panel: {
        background: "linear-gradient(160deg, #0d0720 0%, #160930 60%, #0a0418 100%)",
        border: "1px solid #3a1a5a",
        borderRadius: 14,
        padding: "28px 32px",
        width: "min(480px, 92vw)",
        display: "flex",
        flexDirection: "column",
        gap: 18,
        boxShadow: "0 0 80px rgba(80, 20, 160, 0.3), inset 0 0 40px rgba(60,10,120,0.08)",
    },
    header: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 4,
    },
    shade: {
        fontFamily: "Georgia, serif",
        fontSize: 24,
        color: "#aa66ee",
        letterSpacing: 3,
        textShadow: "0 0 20px rgba(160, 80, 240, 0.4)",
    },
    subtitle: {
        fontFamily: "monospace",
        fontSize: 11,
        color: "#554477",
        letterSpacing: 2,
    },
    dots: {
        fontFamily: "monospace",
        fontSize: 18,
        color: "#7733bb",
        letterSpacing: 4,
        minHeight: 24,
        display: "block",
        textAlign: "center",
    },
    statsRow: {
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    statPill: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: 2,
        background: "rgba(20,8,40,0.6)",
        border: "1px solid #2a1a3a",
        borderRadius: 7,
        padding: "6px 12px",
        flexShrink: 0,
    },
    statLabel: {
        fontFamily: "monospace",
        fontSize: 9,
        color: "#443355",
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    statValue: {
        fontFamily: "Georgia, serif",
        fontSize: 16,
        fontWeight: "bold",
    },
    meterWrapper: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        gap: 5,
    },
    meterLabel: {
        fontFamily: "monospace",
        fontSize: 9,
        color: "#443355",
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    meterTrack: {
        height: 6,
        background: "#0d0420",
        borderRadius: 3,
        overflow: "hidden",
    },
    meterFill: {
        height: "100%",
        borderRadius: 3,
    },
    log: {
        display: "flex",
        flexDirection: "column",
        gap: 7,
        maxHeight: 240,
        overflowY: "auto",
        padding: "4px 0",
    },
    logLine: {
        fontFamily: "Georgia, serif",
        fontSize: 13,
        lineHeight: 1.5,
        display: "flex",
        alignItems: "center",
        gap: 8,
        animation: "fadeInUp 0.2s ease-out",
    },
    logBullet: {
        flexShrink: 0,
        width: 14,
        textAlign: "center",
        opacity: 0.7,
    },
};
